package com.example.pokemoncase.constant

object IntentKey {

    const val KEY_STRING_POKEMON_NAME="KEY_STRING_POKEMON_NAME"
    const val KEY_STRING_POKEMON_FRONT_IMAGE="KEY_STRING_POKEMON_FRONT_IMAGE"
    const val KEY_STRING_POKEMON_BACK_IMAGE="KEY_STRING_POKEMON_BACK_IMAGE"
}